name: gooDo

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Action info
        run: echo "If you are in main, run manually the action on the proper branch"

