name: gooDo

on:
  push:
    paths:
      - 'gooDo/cdk/**/*.ts'
      - 'gooDo/src/**/*.ts'
      - 'gooDo/utils/**/*.ts'
      - .github/workflows/gooDo-stack.yaml
  workflow_dispatch:

env:
  AWS_REGION: eu-west-3
  AWS_STAGE: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{env.AWS_REGION}} 

      - name: Deploy CDK stack
        working-directory: ./gooDo
        run: "npm run cdk-mainStack"
